export const categories = [
  { id: 1, name: "backgrounds" },
  { id: 2, name: "fashion" },
  { id: 3, name: "nature" },
  { id: 4, name: "science" },
  { id: 5, name: "education" },
  { id: 6, name: "feelings" },
  { id: 7, name: "health" },
  { id: 8, name: "people" },
  { id: 9, name: "religion" },
  { id: 10, name: "places" },
  { id: 11, name: "animals" },
  { id: 12, name: "industry" },
  { id: 13, name: "computer" },
  { id: 14, name: "food" },
  { id: 15, name: "sports" },
  { id: 16, name: "transportation" },
  { id: 17, name: "travel" },
  { id: 18, name: "buildings" },
  { id: 19, name: "business" },
  { id: 20, name: "music" },
];