export const categories = [
  { id: 1, name: "Nature" },
  { id: 2, name: "Abstract" },
  { id: 3, name: "Animals" },
  { id: 4, name: "Architecture" },
  { id: 5, name: "Cars" },
  { id: 6, name: "Technology" },
  { id: 7, name: "Space" },
  { id: 8, name: "Flowers" },
  { id: 9, name: "Cityscapes" },
  { id: 10, name: "Minimalist" },
  { id: 11, name: "Textures" },
  { id: 12, name: "Fantasy" },
  { id: 13, name: "Sports" },
  { id: 14, name: "Music" },
  { id: 15, name: "Food & Drink" },
  { id: 16, name: "Underwater" },
  { id: 17, name: "Travel" },
  { id: 18, name: "Vintage" },
  { id: 19, name: "Patterns" },
  { id: 20, name: "Art" },
];
